export const START_ACTION = 'UserCoin/START_ACTION'
export const SUCCESS_ACTION = 'UserCoin/SUCCESS_ACTION'
export const ERROR_ACTION = 'UserCoin/ERROR_ACTION'
export const RESET_ACTION = 'UserCoin/RESET_ACTION'
export const SEARCH_ACTION = 'UserCoin/SEARCH_ACTION'
