export const START_ACTION = 'Tournament/START_ACTION'
export const SUCCESS_ACTION = 'Tournament/SUCCESS_ACTION'
export const ERROR_ACTION = 'Tournament/ERROR_ACTION'
export const RESET_ACTION = 'Tournament/RESET_ACTION'
export const SEARCH_ACTION = 'Tournament/SEARCH_ACTION'
